### ISSUE TITLE
Setup code analysis tools

### ISSUE THREAD

**Issue by alim** [alim/seamaster#4]
Select code analysis tools and setup for the project (e.g. Code Climate or Reek).

**Comment by imranraja85** [comment]
it looks like only the repository owner can set up Code Climate (which has a reek engine)

**Comment by imranraja85** [comment]
I imported the project here: https://codeclimate.com/github/alim/seamaster

**Comment by alim** [comment]
Thanks for setting this up. I added a note to the wiki.
