### ISSUE TITLE
Select user interface library 

### ISSUE THREAD

**Issue by alim** [alim/seamaster#5]

**Comment by joonyou** [comment]
For UI, AngularJS or ReactJS recommended.  To set up ReactJS, https://www.selfthis.com/2016/05/14/setting-up-a-react-project/

**Comment by alim** [comment]
ReactJS is alright. I've always thought Angular adds too much code for very little benefit. I haven't implemented ReactJS in a project, so that would be beneficial.  I'd also be up for trying Polymer, just because it's what we'll have to use at work.

**Comment by imranraja85** [comment]
Want to try turbolinks 5 with polymer? The less JS the better imo :)

**Comment by alim** [comment]
Let's try the turbolinks too. I haven't used it before, but it would be interesting to see how it works. I'm going to go ahead and setup the Polymer gems next.
